services:
  # web:
  #   build: .
  #   ports:
  #     - "${PORT}:5000"
  gpt-load:
    image: ghcr.io/tbphp/gpt-load:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: gpt-load
    # ports:
    #   - "3011:3011"
    network_mode : host
    # env_file:
      # - .env
    restart: always
    volumes:
      - ./data:/app/data
    stop_grace_period: 10s
    healthcheck:
      test: wget -q --spider -T 10 -O /dev/null http://localhost:3011/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      PORT : "3011"
      HOST : "0.0.0.0"
      # 认证配置 是必需的，用于保护管理 API 和 UI 界面
      AUTH_KEY : "${AUTH_KEY}"
      # 数据库配置 默认不填写，使用./data/gpt-load.db的SQLite
      # MySQL 示例:
      DATABASE_DSN : "${DATABASE_DSN}"

  git-server:
    image: codeberg.org/forgejo/forgejo:12
    container_name: forgejo
    # network_mode : host
    environment:
      USER_UID : "${USER_UID}" 
      USER_GID : "${USER_GID}"
      FORGEJO__database__DB_TYPE : "${FORGEJO__database__DB_TYPE}"
      FORGEJO__database__HOST : "${FORGEJO__database__HOST}"
      FORGEJO__database__NAME : "${FORGEJO__database__NAME}"
      FORGEJO__database__USER : "${FORGEJO__database__USER}"
      FORGEJO__database__PASSWD : "${FORGEJO__database__PASSWD}"
    restart: always
    # networks:
      # - forgejo
    volumes:
      - ./forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

  # lobe-chat:
  #   image: "lobehub/lobe-chat"
  #   network_mode : host
  #   # env_file:
  #   #   - .env
  #   environment:
  #     DATABASE_URL : "${DATABASE_URL}"
  #     APP_URL : "${APP_URL}"
  #     KEY_VAULTS_SECRET : "${KEY_VAULTS_SECRET}"
  #     NEXT_PUBLIC_SERVICE_MODE : "${NEXT_PUBLIC_SERVICE_MODE}"
  #     S3_SECRET_ACCESS_KEY : "${S3_SECRET_ACCESS_KEY}"
  #     S3_ACCESS_KEY_ID : "${S3_ACCESS_KEY_ID}"
  #     S3_PUBLIC_DOMAIN : "${S3_PUBLIC_DOMAIN}"
  #     S3_ENDPOINT : "${S3_ENDPOINT}"
  #     S3_BUCKET : "${S3_BUCKET}"
  #     CLERK_WEBHOOK_SECRET : "${CLERK_WEBHOOK_SECRET}"
  #     CLERK_SECRET_KEY : "${CLERK_SECRET_KEY}" 
  #     NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY : "${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}"


    # ports:
      # - "3210:3210"

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    network_mode : host

    # ports:
      # - "80:80"          # HTTP
      # - "443:443"        # HTTPS
      # - "443:443/udp"    # HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # 映射 Caddy 配置文件
      - ./caddy-data:/data             # 持久化证书等数据
      - ./caddy-config:/config         # 持久化配置状态
